### ISSUE TITLE
update filecoin-solidity to v4.0.2

### ISSUE THREAD

**Issue by raulk** [filecoin-project/fvm-starter-kit-deal-making#3]

**Comment by xBalbinus** [comment]
https://github.com/filecoin-project/fvm-starter-kit-deal-making/pull/6/files

**Comment by polus-arcticus** [comment]
https://github.com/filecoin-project/fvm-starter-kit-deal-making/pull/7

I added some changes that gets the deal-client compiling again :smiley:
